#!/run/current-system/sw/bin/bash
set -euo pipefail
mkdir -p "$HOME/Pictures/Screenshots"
file="$HOME/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S-%N).png"
if [[ "${1:-full}" == region ]]; then
    geometry=$(slurp) || exit 0
    grim -g "$geometry" "$file"
    wl-copy --type image/png < "$file"
    swappy -f "$file" -o "$file"
else
    grim "$file"
    wl-copy --type image/png < "$file"
fi
notify-send 'Screenshot saved' "$file"
