-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
        },
    },
})

-- Monitors
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "2560x1440@240.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
