general {
    hide_cursor = true
}
background {
    monitor =
    color = rgba(1b2028ff)
}
input-field {
    monitor =
    size = 320, 54
    position = 0, -40
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgba(91a7bfff)
    inner_color = rgba(272e38ff)
    font_color = rgba(e5e9efff)
    font_family = JetBrainsMono Nerd Font
    placeholder_text = Password
    rounding = 8
}
label {
    monitor =
    text = $TIME
    font_size = 56
    font_family = JetBrainsMono Nerd Font
    color = rgba(e5e9efff)
    position = 0, 100
    halign = center
    valign = center
}
